# Site settings
title: NDA
description: Nicolas De Angelis' webpage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username_title: Nicolas <br> De Angelis
username: Nicolas De Angelis
user_description: I am currently pursuing a Postdoctoral researcher in the HERTAG group at the Institute for Space Astrophysics and Planetology (<b>IAPS</b>) of the <b>Italian National Institute for Astrophysics</b> in Rome, Italy. My research interests lie at the exciting intersection of high-energy astrophysics and space-based instrumentation. One key aspect of my work involves the development of the next-generation Compton polarimeters, such as POLAR-2 and CUSP, aiming the respectively measure the hard X-ray polarization of the prompt emission of Gamma-Ray Bursts (GRBs) and of Solar Flares. I have been extensively involved in various facets of these projects, including the characterization of Silicon Photomultipliers (SiPMs), Multi-Anode Photomultipliers (MAPMTs), or Avalanche PhotoDiodes (APDs), optical characterization and simulation using Geant4, and the implementation of data acquisition systems using ASIC/FPGA-based electronics. Additionally, I contribute to the rigorous space qualification campaigns of POLAR-2, ensuring its reliability and robustness through irradiation, vibration and shock testing, as well as thermal vacuum cycling. I am also actively involved in the mechanical assembly and design of the polarimeter as well as in gamma-ray datector calibration. I am also actively engaged in the data analysis of the POLAR mission, predecessor of POLAR-2. Additionally, I am involved in the development of other future space-based experiments such as PHEMTO (the Polarimetric High Energy Modular Telescope Observatory).
user_title: Postdoctoral researcher in high-energy astrophysics
email: nicolas.deangelis@unige.ch
#twitter_username: lorem_ipsum
github_username:  ndeangel
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']


# show_timeline_card:
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
docs_download_link: docs/


timeline:
  title: "Timeline"
  text: "Lorem ipsum timeline"
  section: timeline
  # left is the default
  #start_align: "left"
  events:
    - title: "Our Humble Beginnings"
      year: "2009-2011"
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
      image: assets/img/timeline/1.jpg
      alt:
    - title: "An Agency is Born"
      year: "March 2011"
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
      image: assets/img/timeline/2.jpg
      alt:
    - title: "Jekyll Theme is created"
      year: "2019"
      desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
      image: assets/img/timeline/3.jpg
      alt: image alt text
    - title: "Title"
      year: "2009-2011"
      desc: "Your description here, **Markdown** is fully supported."
      image: assets/img/timeline/4.jpg
      alt:
      # you can enforce the alignment
      align: right
  end: "Be Part <br> of Our <br> Story!"

